// Copyright (C) 2021 Umang Raghuvanshi.
// This file is a part of the mach-rs project and is licensed under the MIT license.
// See the LICENSE file in the project root for details.

#include <mach/mach.h>

#include <mach/audit_triggers_types.h>
#include <mach/boolean.h>
#include <mach/bootstrap.h>
#include <mach/clock.h>
#include <mach/clock_priv.h>
#include <mach/clock_reply.h>
#include <mach/clock_types.h>
#include <mach/dyld_kernel.h>
#include <mach/error.h>
#include <mach/exc.h>
#include <mach/exception.h>
#include <mach/exception_types.h>
#include <mach/host_info.h>
#include <mach/host_notify.h>
#include <mach/host_priv.h>
#include <mach/host_reboot.h>
#include <mach/host_security.h>
#include <mach/host_special_ports.h>
#include <mach/kern_return.h>
#include <mach/kmod.h>
#include <mach/lock_set.h>
#include <mach/mach_error.h>
// #include <mach/mach_eventlink.h>
#include <mach/mach_host.h>
#include <mach/mach_init.h>
#include <mach/mach_interface.h>
#include <mach/mach_param.h>
#include <mach/mach_port.h>
#include <mach/mach_right.h>
#include <mach/mach_syscalls.h>
#include <mach/mach_time.h>
#include <mach/mach_traps.h>
#include <mach/mach_types.h>
#include <mach/mach_vm.h>
#include <mach/mach_voucher.h>
#include <mach/mach_voucher_types.h>
#include <mach/machine.h>
#include <mach/memory_entry.h>
#include <mach/memory_object_types.h>
#include <mach/message.h>
#include <mach/mig.h>
#include <mach/mig_errors.h>
#include <mach/mig_strncpy_zerofill_support.h>
#include <mach/mig_voucher_support.h>
#include <mach/ndr.h>
#include <mach/notify.h>
#include <mach/policy.h>
#include <mach/port.h>
#include <mach/port_obj.h>
#include <mach/processor.h>
#include <mach/processor_info.h>
#include <mach/processor_set.h>
#include <mach/rpc.h>
#include <mach/semaphore.h>
#include <mach/std_types.h>
#include <mach/sync.h>
#include <mach/sync_policy.h>
#include <mach/task.h>
#include <mach/task_info.h>
#include <mach/task_inspect.h>
#include <mach/task_policy.h>
#include <mach/task_special_ports.h>
#include <mach/thread_act.h>
#include <mach/thread_info.h>
#include <mach/thread_policy.h>
#include <mach/thread_special_ports.h>
#include <mach/thread_state.h>
#include <mach/thread_status.h>
#include <mach/thread_switch.h>
#include <mach/time_value.h>
#include <mach/vm_attributes.h>
#include <mach/vm_behavior.h>
#include <mach/vm_inherit.h>
#include <mach/vm_map.h>
#include <mach/vm_page_size.h>
#include <mach/vm_param.h>
#include <mach/vm_prot.h>
#include <mach/vm_purgable.h>
#include <mach/vm_region.h>
#include <mach/vm_statistics.h>
#include <mach/vm_sync.h>
#include <mach/vm_task.h>
#include <mach/vm_types.h>