name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_prebuilt:

    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  test_bindgen:

    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v2
    - name: Build bindings and test
      run: cargo test --verbose --features bindgen
